name: APK Builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fix Network and Install Aidl
        # Bağlantı hatalarını önlemek için DNS ve paket listesini tazeliyoruz
        run: |
          sudo echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          sudo apt-get update || (sleep 10 && sudo apt-get update)
          sudo apt-get install -y aidl python3-pip

      - name: Build with Buildozer
        # Internet hatası riskine karşı Buildozer'ı daha toleranslı çalıştırıyoruz
        uses: kivy/buildozer-action@master
        with:
          command: android debug
          repository_root: .

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
