name: APK Builder
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Aidl and System Dependencies
        # Aidl hatasını manuel kurulumla kökten çözüyoruz
        run: |
          sudo apt-get update
          sudo apt-get install -y aidl python3-pip

      - name: Build with Buildozer
        # Kivy'nin resmi aracını kullanarak tüm süreci Buildozer'a bırakıyoruz
        uses: kivy/buildozer-action@master
        with:
          command: android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
